javac.exe tage\*.java
javac.exe tage\input\*.java
javac.exe tage\input\action\*.java
javac.exe tage\networking\*.java
javac.exe tage\networking\client\*.java
javac.exe tage\networking\server\*.java
javac.exe tage\nodeControllers\*.java
javac.exe tage\shapes\*.java
javac.exe tage\objectRenderers\*.java
javac.exe tage\physics\*.java
javac.exe tage\physics\JBullet\*.java
javac.exe tage\rml\*.java
javac.exe tage\ai\behaviortrees\*.java
javac.exe tage\audio\*.java
javac.exe tage\audio\joal\*.java
